chore: cleanup

diff --git a/bin/md-to-pdf-eisvogel b/bin/md-to-pdf-eisvogel
--- a/bin/md-to-pdf-eisvogel
+++ b/bin/md-to-pdf-eisvogel
@@ -1,19 +1,18 @@
 #!/usr/bin/env bash
 
 if [ $# -ne 1 ]; then
-	echo "Correct number of arguments not specified"
-	echo "Usage: $0 <markdown-file>"
-	exit
+    echo "Correct number of arguments not specified"
+    echo "Usage: $0 <markdown-file>"
+    exit
 fi
 
-outfile=$(basename $1 .md)
+outfile=$(basename "$1" .md)
 
 echo "Converting file using pandoc and eisvogel template"
 
-pandoc $1 -o $outfile-generated.pdf --from markdown+yaml_metadata_block+raw_html --template eisvogel --highlight-style  pygments
+pandoc "$1" -o "${outfile-generated}.pdf" \
+    --from markdown+yaml_metadata_block+raw_html \
+    --template eisvogel \
+    --highlight-style  pygments
 
-if [ $? -eq 0 ]; then
-	echo "Generated file $outfile-generated.pdf"
-else
-	echo "Failed to generate pdf"
-fi
+[[ $? -eq 0 ]] && echo "Generated file $outfile-generated.pdf" || echo "Failed to generate pdf"
diff --git a/bin/md-to-pdf-typst b/bin/md-to-pdf-typst
--- a/bin/md-to-pdf-typst
+++ b/bin/md-to-pdf-typst
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
 if [ $# -ne 1 ]; then
-	echo "Correct number of arguments not specified"
-	echo "Usage: $0 <markdown-file>"
-	exit
+    echo "Correct number of arguments not specified"
+    echo "Usage: $0 <markdown-file>"
+    exit
 fi
 
 outfile=$(basename "$1" .md)
@@ -12,10 +12,14 @@ echo "Converting file using pandoc and Typst"
 
 tmpfile=$(mktemp)
 
-pandoc "$1" -o "$tmpfile" --from markdown+yaml_metadata_block+raw_html --to typst
-[[ "$?" -ne 0 ]] && echo "Could not convert from md to typ" && exit 1
+if ! pandoc "$1" -o "$tmpfile" --from markdown+yaml_metadata_block+raw_html --to typst; then
+    echo "Could not convert from md to typ"
+    exit 1
+fi
 
-typst compile "$tmpfile" "./${outfile}.pdf"
-[[ "$?" -ne 0 ]] && echo "Could not convert from typ to pdf" && exit 1
+if ! typst compile "$tmpfile" "./${outfile}.pdf"; then
+    echo "Could not convert from typ to pdf"
+    exit 1
+fi
 
 echo "Generated file $outfile-generated.pdf"
